<?php

return [
    'Getting Started' => [
        'url' => '/getting-started',
        'children' => [
            
        ],
    ],
    'Architecture Patterns' => [
        'url' => '/architecture-patterns',
        'children' => [
            'Client Server Architecture' => 'architecture-patterns/client-server-architecture',
            'Microservices Architecture' => 'architecture-patterns/microservices-architecture',
            'Monolithic Architecture' => 'architecture-patterns/monolithic-architecture',
            'Serverless Architecture' => 'architecture-patterns/serverless-architecture',
            'Service Oriented Architecture' => 'architecture-patterns/service-oriented-architecture',
        ],
    ],
    'System Components' => [
        'url' => '/system-components',
        'children' => [
            'Content Delivery Network (CDN)' => 'system-components/cdn',
            'Block Storage' => 'system-components/block-storage',
            'Object Storage' => 'system-components/object-storage',
            'Document Storage' => 'system-components/document-storage',
            'Graph Database' => 'system-components/graph-database',
            'In-Memory Cache' => 'system-components/in-memory-cache',
            'Message Queue' => 'system-components/message-queue',
            'Key-Value Store' => 'system-components/key-value-store',
            'Relational Database' => 'system-components/relational-database',
            'Search Engine Database' => 'system-components/search-engine-database',
            'Wide Column Database' => 'system-components/wide-column-database',
            'Enterprise Service Bus' => 'system-components/enterprise-service-bus',
            'Load Balancer' => 'system-components/load-balancer',
            'Server' => 'system-components/server',
            'Service' => 'system-components/service',
            'Virtual Private Cloud (VPC)' => 'system-components/virtual-private-cloud',
            'Virtual Machine (VM)' => 'system-components/virtual-machine',
            'Web Application' => 'system-components/web-application',
        ],
    ],
    'Glossary' => [
        'url' => '/glossary',
        'children' => [
            'Abstraction' => 'glossary/abstraction',
            'ACID' => 'glossary/acid',
            'API' => 'glossary/api',
            'Architecture' => 'glossary/architecture',
            'Authentication' => 'glossary/authentication',
            'Authorization' => 'glossary/authorization',
            'BASE' => 'glossary/base',
            'Capacity Planning' => 'glossary/capacity-planning',
            'Cohesion' => 'glossary/cohesion',
            'Compatibility' => 'glossary/compatibility',
            'Component' => 'glossary/component',
            'Concurrency' => 'glossary/concurrency',
            'Consistency' => 'glossary/consistency',
            'Coupling' => 'glossary/coupling',
            'Data Integrity' => 'glossary/data-integrity',
            'Data Modeling' => 'glossary/data-modeling',
            'Decryption' => 'glossary/decryption',
            'Dependency' => 'glossary/dependency',
            'Design Pattern' => 'glossary/design-pattern',
            'Distributed System' => 'glossary/distributed-system',
            'Encryption' => 'glossary/encryption',
            'Fault Tolerance' => 'glossary/fault-tolerance',
            'Firewall' => 'glossary/firewall',
            'Functional Requirement' => 'glossary/functional-requirement',
            'Interface' => 'glossary/interface',
            'Latency' => 'glossary/latency',
            'Load Balancing' => 'glossary/load-balancing',
            'Logging' => 'glossary/logging',
            'Model' => 'glossary/model',
            'Module' => 'glossary/module',
            'Non-functional Requirement' => 'glossary/non-functional-requirement',
            'Performance' => 'glossary/performance',
            'PostgreSQL' => 'glossary/postgresql',
            'Redundancy' => 'glossary/redundancy',
            'Reliability' => 'glossary/reliability',
            'Replication' => 'glossary/replication',
            'Requirements' => 'glossary/requirements',
            'Scalability' => 'glossary/scalability',
            'Security' => 'glossary/security',
            'Service Level Agreement' => 'glossary/service-level-agreement',
            'System Design' => 'glossary/system-design',
            'Throughput' => 'glossary/throughput',
            'Tier' => 'glossary/tier',
            'UML' => 'glossary/uml',
            'Use Case' => 'glossary/use-case',
        ],
    ],
];
