<?php

return [
    'Getting Started' => [
        'url' => 'docs/getting-started',
        'children' => [
            'Customizing Your Site' => 'docs/customizing-your-site',
            'Navigation' => 'docs/navigation',
            'Algolia DocSearch' => 'docs/algolia-docsearch',
            'Custom 404 Page' => 'docs/custom-404-page',
        ],
    ],
    'Glossary' => [
        'url' => '/glossary',
        'children' => [
            'Abstraction' => 'glossary/abstraction',
            'ACID' => 'glossary/acid',
            'API' => 'glossary/api',
            'Architecture' => 'glossary/architecture',
            'Authentication' => 'glossary/authentication',
            'Authorization' => 'glossary/authorization',
            'BASE' => 'glossary/base',
            'Capacity Planning' => 'glossary/capacity-planning',
            'Cohesion' => 'glossary/cohesion',
            'Compatibility' => 'glossary/compatibility',
            'Component' => 'glossary/component',
            'Concurrency' => 'glossary/concurrency',
            'Consistency' => 'glossary/consistency',
            'Coupling' => 'glossary/coupling',
            'Data Integrity' => 'glossary/data-integrity',
            'Data Modeling' => 'glossary/data-modeling',
            'Decryption' => 'glossary/decryption',
            'Dependency' => 'glossary/dependency',
            'Design Pattern' => 'glossary/design-pattern',
            'Distributed System' => 'glossary/distributed-system',
            'Encryption' => 'glossary/encryption',
            'Fault Tolerance' => 'glossary/fault-tolerance',
            'Firewall' => 'glossary/firewall',
            'Functional Requirement' => 'glossary/functional-requirement',
            'Interface' => 'glossary/interface',
            'Latency' => 'glossary/latency',
            'Load Balancing' => 'glossary/load-balancing',
            'Logging' => 'glossary/logging',
            'Model' => 'glossary/model',
            'Module' => 'glossary/module',
            'Non-functional Requirement' => 'glossary/non-functional-requirement',
            'Performance' => 'glossary/performance',
            'PostgreSQL' => 'glossary/postgresql',
            'Redundancy' => 'glossary/redundancy',
            'Reliability' => 'glossary/reliability',
            'Replication' => 'glossary/replication',
            'Requirements' => 'glossary/requirements',
            'Scalability' => 'glossary/scalability',
            'Security' => 'glossary/security',
            'System Design' => 'glossary/system-design',
            'Throughput' => 'glossary/throughput',
            'Tier' => 'glossary/tier',
            'UML' => 'glossary/uml',
            'Use Case' => 'glossary/use-case',
        ],
    ],
    'Jigsaw Docs' => 'https://jigsaw.tighten.co/docs/installation',
];
